stages:
  - compile
  - performance

compile:
  stage: compile
  tags:
    - visionfive2
  script:
    - ./scripts/yacc_gen.sh
    - python3 ./scripts/execute.py --no-test
  artifacts:
    paths:
      - syc

performance:
  stage: performance
  tags:
    - rv64gc
  script:
    - chmod +x ./scripts/benchmark.sh
    - ./scripts/benchmark.sh
    - cp /home/share/result.csv .

  dependencies:
    - compile

  artifacts:
    paths:
      - result.csv
