name: check-compile
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Bison and Flex
        run: sudo apt-get install bison flex

      - name: Generate Parser
        run: bash scripts/yacc_gen.sh

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build -j8

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Flatten
        run: python scripts/flatten.py --input_dir src --output_dir flattened

      - name: Compile Flattened Source
        run: python scripts/compile.py
  
