name: check-compile
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Bison and Flex
        run: sudo apt-get install bison flex

      - name: Generate Parser
        run: bash scripts/yacc_gen.sh

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build -j8
